export const posts = [
  {
    id: 1,
    title: 'Excited for the new project launch!',
    content: 'The team has been working hard on the upcoming project launch. Stay tuned for updates!',
    image: 'https://picsum.photos/seed/project-launch/500',
    likes: 10,
    dislikes: 2,
  },
  {
    id: 2,
    title: 'Team building event tomorrow!',
    content: 'Don\'t forget about the team building event tomorrow at the company park. Bring your enthusiasm!',
    image: 'https://picsum.photos/seed/team-building/500',
    likes: 15,
    dislikes: 3,
  },
  {
    id: 3,
    title: 'Company picnic this weekend!',
    content: 'Join us for a fun-filled day at the annual company picnic. Games, food, and camaraderie await!',
    image: 'https://picsum.photos/seed/company-picnic/500',
    likes: 8,
    dislikes: 5,
  },
  {
    id: 4,
    title: 'Coffee break with the CEO',
    content: 'Have questions or suggestions? Join us for a coffee break with the CEO this Thursday at the cafeteria!',
    image: 'https://picsum.photos/seed/coffee-break/500',
    likes: 8,
    dislikes: 5,
  },
  // Add more posts as needed
  {
    id: 5,
    title: 'New employee orientation next week!',
    content: 'Welcome to all our new hires! Get ready for an exciting week of orientation activities and introductions to the team.',
    image: 'https://picsum.photos/seed/new-employee/500',
    likes: 12,
    dislikes: 1,
  },
  {
    id: 6,
    title: 'Volunteer opportunity: Habitat for Humanity',
    content: 'Join us for a day of volunteering with Habitat for Humanity next Saturday. Make a difference in our community!',
    image: 'https://picsum.photos/seed/volunteer-opportunity/500',
    likes: 7,
    dislikes: 3,
  },
  {
    id: 7,
    title: 'Lunch and learn session: Cybersecurity best practices',
    content: 'Learn how to protect yourself and the company from cyber threats. Lunch will be provided!',
    image: 'https://picsum.photos/seed/cybersecurity-lunch/500',
    likes: 11,
    dislikes: 2,
  },
  {
    id: 8,
    title: 'Employee recognition awards ceremony',
    content: 'Nominate your colleagues for outstanding performance! The awards ceremony will be held next month.',
    image: 'https://picsum.photos/seed/employee-awards/500',
    likes: 9,
    dislikes: 4,
  },
  {
    id: 9,
    title: 'Product launch party',
    content: 'Celebrate the launch of our latest product with a party in the office. Food, drinks, and music provided!',
    image: 'https://picsum.photos/seed/product-launch-party/500',
    likes: 14,
    dislikes: 2,
  },
  {
    id: 10,
    title: 'Team bonding retreat in the mountains',
    content: 'Escape the hustle and bustle of the city and join us for a team bonding retreat in the mountains. Get ready for hiking, campfires, and team-building activities!',
    image: 'https://picsum.photos/seed/team-bonding-retreat/500',
    likes: 6,
    dislikes: 2,
  },
  {
    id: 11,
    title: 'Excited for the new project launch!',
    content: 'The team has been working hard on the upcoming project launch. Stay tuned for updates!',
    image: 'https://picsum.photos/seed/project-launch/500',
    likes: 10,
    dislikes: 2,
  },
  {
    id: 12,
    title: 'Team building event tomorrow!',
    content: 'Don\'t forget about the team building event tomorrow at the company park. Bring your enthusiasm!',
    image: 'https://picsum.photos/seed/team-building/500',
    likes: 15,
    dislikes: 3,
  },
  {
    id: 13,
    title: 'Company picnic this weekend!',
    content: 'Join us for a fun-filled day at the annual company picnic. Games, food, and camaraderie await!',
    image: 'https://picsum.photos/seed/company-picnic/500',
    likes: 8,
    dislikes: 5,
  },
  {
    id: 14,
    title: 'Coffee break with the CEO',
    content: 'Have questions or suggestions? Join us for a coffee break with the CEO this Thursday at the cafeteria!',
    image: 'https://picsum.photos/seed/coffee-break/500',
    likes: 8,
    dislikes: 5,
  },
  // Add more posts as needed
  {
    id: 15,
    title: 'New employee orientation next week!',
    content: 'Welcome to all our new hires! Get ready for an exciting week of orientation activities and introductions to the team.',
    image: 'https://picsum.photos/seed/new-employee/500',
    likes: 12,
    dislikes: 1,
  },
];
